apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: semperis-ns
spec:
  selector: 
    matchLabels:
      app: postgres-db
  replicas: 1  # Single replica for the database
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres
        env:
        - name: POSTGRES_USER
          value: "idubi"
        - name: POSTGRES_PASSWORD
          value: "idubi"
        - name: POSTGRES_DB
          value: "idubi"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: semperis-ns
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP 
      port: 5432
      targetPort: 5432
