apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: semperis-ns
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer