version: "3"

services:
  web-app:
    container_name: web-app
    image: idubi/flask-crud:lts
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "5000:5000"
    environment:
      DB_USER: idubi
      DB_PASSWORD: idubi
      DB_NAME: idubi
      DB_TYPE: postgresql
      DB_HOST: postgres-db
      DB_PORT: 5432
    depends_on:
      - postgres-db
    restart: On-failure
    networks:
      - flask-ntwrk
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: idubi
      POSTGRES_PASSWORD: idubi
      POSTGRES_DB: idubi
    ports:
      - "5432:5432"
    networks:
      - flask-ntwrk
networks:
  flask-ntwrk:
    driver: bridge
