version: "3"

services:
  web-app:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        CACHEBUST: $RANDOM
    ports:
      - "5000:5000"
    environment:
      DB_USER: idubi
      DB_PASSWORD: idubi
      DB_NAME: idubi
      DB_TYPE: postgresql
      DB_HOST: postgres-db
      DB_PORT: 5432
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: idubi
      POSTGRES_PASSWORD: idubi
      POSTGRES_DB: idubi
    ports:
      - "5432:5432"
